os:
  - linux
  - osx

sudo: false
env:
  global:
    - MAKE="make -j 2"

addons:
  homebrew:
    packages:
      - shared-mime-info

language: ruby
rvm:
  - 2.4.10
  - 2.5.8
  - 2.6.6
  - 2.7.2
  - 3.0.0
  #- ruby-head

gemfile:
  - gemfiles/no_rails.gemfile
  - gemfiles/rails_5.gemfile
  - gemfiles/rails_6.gemfile

matrix:
  fast_finish: true

  allow_failures:
    - rvm: 3.0.0

  exclude:
    - gemfile: gemfiles/no_rails.gemfile
      rvm: 2.4.10
      os: osx
    - gemfile: gemfiles/rails_5.gemfile
      rvm: 2.4.10
      os: osx
    - gemfile: gemfiles/rails_5.gemfile
      rvm: 2.5.8
      os: osx
    # Rails 6 only support Ruby 2.5 and above.
    - gemfile: gemfiles/rails_6.gemfile
      rvm: 2.4.10
    - os: osx
      rvm: 2.4.10
    - os: osx
      rvm: 3.0.0
