rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby
  - rbx
  - rbx-19mode
  - ree

env:
  - JRUBY_OPTS="--1.8 -Xcext.enabled=true"

script:
  - gem build oj.gemspec
  - gem install oj-*
#  - ruby test/tests.rb
#  - ruby test/test_fast.rb
#  - ruby test/test_mimic.rb
