os:
  - linux
  - osx

sudo: false
env:
  global:
    - MAKE="make -j 2"

language: ruby
rvm:
  #- 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.2
  - 2.5.1
  - ruby-head

gemfile:
  - gemfiles/no_rails.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.gemfile

matrix:
  fast_finish: true
  allow_failures:
    - rvm: 2.1.10
    - rvm: 2.2.6
    - rvm: ruby-head

  exclude:
    - gemfile: gemfiles/rails_5.gemfile
      rvm: 2.1.10
    - gemfile: gemfiles/no_rails.gemfile
      rvm: 2.1.10
    - gemfile: gemfiles/no_rails.gemfile
      rvm: 2.2.6
    - gemfile: gemfiles/no_rails.gemfile
      rvm: 2.3.3
    - gemfile: gemfiles/no_rails.gemfile
      rvm: 2.4.2
    - gemfile: gemfiles/rails_4.1.gemfile
      rvm: 2.4.2
      os: osx
    - gemfile: gemfiles/rails_4.2.gemfile
      rvm: 2.4.2
      os: osx
    - gemfile: gemfiles/rails_4.2.gemfile
      rvm: 2.4.2
      os: linux
