rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - rbx
  - rbx-19mode

script:
  - gem build oj.gemspec
  - gem install oj-*
#  - ruby test/tests.rb
#  - ruby test/test_fast.rb
#  - ruby test/test_mimic.rb
